### ISSUE TITLE
Functions not exported and wrong examples

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#100]
The functions `get_events_table()`, `muts_to_sticks()`, `plot_sticks()`, and `plot_vaf()` are not exported in file `NAMESPACE`.

Moreover, their examples contain some syntactic errors and could be better indented and commented on.

Please use the following bash command in the rRACES directory and verify the new documentation in the directory `docs` before any commit.

```{bash}
make site 
```

**Comment by albertocasagrande** [comment]
All of the cited functions still need to be fixed. Please consider the code reported in the functions documentation as an example of the issue.

**Comment by riccardobergamin** [comment]
do we export only plot_vaf and integrate plot_sticks with plot_forest?
