### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#103]
i am getting this error after the last update when i load the package locally with devtools::load_all()

> Re-compiling` rRACES

─  installing *source* package ‘rRACES’ ...
   ** using staged installation
   ++ set -e
   ++ which cmake
   /usr/local/bin/cmake
   ++ '[' '!' -d RACES ']'
   ++ /Library/Frameworks/R.framework/Resources/bin/R --vanilla --silent -e 'Rcpp::compileAttributes()'
   > Rcpp::compileAttributes()
   > 
   > 
>   ** libs
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c cna.cpp -o cna.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c genomic_data_storage.cpp -o genomic_data_storage.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c logics.cpp -o logics.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c logics_impl.cpp -o logics_impl.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c mutants.cpp -o mutants.o
   clang++ -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I/usr/local/include  -I../_install/include/ -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c mutation_engine.cpp -o mutation_engine.o
   In file included from mutation_engine.cpp:27:
   ../_install/include/read_simulator.hpp:1048:26: warning: loop variable 'mismatch' is always a copy because the range of type 'const std::vector<bool>' does not return a reference [-Wrange-loop-analysis]
           for (const auto& mismatch: mismatch_vector) {
                            ^
   ../_install/include/read_simulator.hpp:1048:14: note: use non-reference type 'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >'
           for (const auto& mismatch: mismatch_vector) {
                ^~~~~~~~~~~~~~~~~~~~~
   ../_install/include/read_simulator.hpp:1102:26: warning: loop variable 'mismatch' is always a copy because the range of type 'const std::vector<bool>' does not return a reference [-Wrange-loop-analysis]
           for (const auto& mismatch : mismatch_vector) {
                            ^
   ../_install/include/read_simulator.hpp:1102:14: note: use non-reference type 'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >'
           for (const auto& mismatch : mismatch_vector) {
                ^~~~~~~~~~~~~~~~~~~~~~
   In file included from mutation_engine.cpp:34:
   In file included from ./mutation_engine.hpp:28:
   ./sid.hpp:23:10: error: 'sid.hpp' file not found with <angled> include; use "quotes" instead
   #include <sid.hpp>
            ^~~~~~~~~
            "sid.hpp"
   ./sid.hpp:24:10: fatal error: 'mutation_spec.hpp' file not found
   #include <mutation_spec.hpp>
            ^~~~~~~~~~~~~~~~~~~
   2 warnings and 2 errors generated.
   make: *** [mutation_engine.o] Error 1
   ERROR: compilation failed for package ‘rRACES’
─  removing ‘/private/var/folders/b1/qw7wc3td0szcvw17h0698lmm0000gn/T/RtmpLYzA6r/devtools_install_5955444f26a/rRACES’
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'R' failed
---
Exit status: 1
stdout & stderr: <printed>

>

**Comment by albertocasagrande** [comment]
Remove the directories `_install`, `_builds`, and `RACES` and retry

**Comment by riccardobergamin** [comment]
ok,it solved the issue! Thnk you very much
