### ISSUE TITLE
Absolute coordinates for chromosomes

### ISSUE THREAD

**Issue by jovoni** [caravagnalab/rRACES#109]
It would be useful, in order to improve the plotting functions, to have a getter for a data frame or similar that stores information regarding the absolute coordinates of the chromosomes. 
This should take account of the genome reference used for sequencing (GRCh37 or GRCh38).
Here's an example of the desired output for the first 5 chromosomes

```
  chr      length      from         to centromerStart centromerEnd
  <chr>     <dbl>     <dbl>      <dbl>          <dbl>        <dbl>
1 chr1  248956422         0  248956422      122026459    124849229
2 chr2  242193529 248956422  491149951      341144567    341144567
3 chr3  198295559 491149951  689445510      581922409    582703370
4 chr4  190214555 689445510  879660065      739157571    739157571
5 chr5  181538259 879660065 1061198324      926145965    929381368
```

**Comment by albertocasagrande** [comment]
rRACES does not deal with centromeres, so it should not return them. I prefer to provide functions with an optional parameter for the centromere data. If you are interested, we can implement a function returning the data frame exclusively containing the chromosome absolute coordinates.

**Comment by caravagn** [comment]
This data frame should only be available for plotting purposes. @jovoni if you manage to get yourself the coordinates just add the data frame as "data" to the package. As we have done in CNAqc. If you are not sure about the coordinates it does not matter, we can check them later on.

**Comment by caravagn** [comment]
It's just for visualization purposes and it's OK that the Rcpp does not use it. We can discuss it at a later stage.
