### ISSUE TITLE
`get_firings`: get number of stochastic events (cell division, death) per species.

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#11]
Proposed format, `event` has to be some literal encoding of a formula. 
```
event | species | epistate  | firings
growth | A | + | 140
death | A | + | 1440
growth | A | - | 140
death | A | - | 144440
switch+- | A | + | 23432
switch-+ | A | - | 23432
```
Decide if these have to be relative to the last stop, or cumulative for the overall simulation. I think cumulative makes sense.

Visualisation: `plot_firings`

**Comment by albertocasagrande** [comment]
What do you mean by growth? All the species mutations and epigenetic state changes occur during a duplication. Should these cases be considered growth or switch?

**Comment by caravagn** [comment]
Apologize yeah I got confused. Just the events you have it is ok. I think that can help if once wants to run a sim and see how many switched that have been, for example. If they are coordinated with cell divisions it does not matter. I gues it's just different type of divisions.

**Comment by albertocasagrande** [comment]
I still do not understand how to count duplications. If a duplication leading to a switch occurs, should we account it as a duplication or a switch?

**Comment by albertocasagrande** [comment]
I suggest to replace `switch+-` and `switch-+` with `switch`. The meaning of switch is clear from the context: in the rows with epistate `-`, the meaning will be `switch-+` and the other way round.
