### ISSUE TITLE
Improvements `simulate_seq` function

### ISSUE THREAD

**Issue by jovoni** [caravagnalab/rRACES#118]
I and @valerianilucrezia were discussing with @caravagn about what would be useful for the `simulate_seq` function to return.

As today, it returns only the sequencing results, but we feel like it would be useful if maybe it returned a list containing:
- seq_results (current output)
- sequencing_info (Sequencer, coverage, purity, read_size)
- genome_reference_positions (absolute chromosome position for the reference used, object now return by the `get_absolute_chromosome_positions` method over a `Rcpp_PhylogeneticForest` object (which is also the input of the `simulate_seq` function))

We think that this additional informations could be useful both for keeping track of the sequencing setup and to remove an eventual dependency of genome wide plotting functions over the `Rcpp_PhylogeneticForest` object.

What do you think?

**Comment by caravagn** [comment]
I would encapsulate this in an Robject

**Comment by albertocasagrande** [comment]
@jovoni, @valerianilucrezia, @caravagn, I'm afraid I have to disagree with this proposal. 

The sequencing info part consists of the `simulation_seq` parameters, and as you have noticed, the genome reference positions are obtained from the phylogenetic forest. A function returning its actual parameters introduces unnecessary code and data structure complexity. In this specific case, it also obfuscates the `simulation_seq` output.

The plotting functions should not be dependent on the phylogenetic forest.  The absolute chromosome positions should be optional, with the only goal of producing *nicer* plots.

**Comment by caravagn** [comment]
Let's schedule a call for 4pm today on this. @jovoni Arrange it.

**Comment by albertocasagrande** [comment]
Closed by commit 403fc150c0ce06ba1780b20bab83740d82738228
