### ISSUE TITLE
Suggested function `add_species(sim, species)`

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#12]
@caravagn wrote in the `nobuild/test.R` file

```R
# Create a species object with the required parameters
# species <- list(
#   name = "B",
#   epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
#   growth_rates = c("+" = 0.1, "-" = 0.3),
#   death_rates = c("+" = 0.05, "-" = 0.1)
# )
# 
# # Call the R wrapper function with the simulation object and the prepared species object
# add_species(sim, species)
```

Should we add a `Simulation` method that takes a list as a parameter?

**Comment by caravagn** [comment]
I would rather add species one by one.

I proposed we agree on the constructor

```
sim$add_species(name="A",
                epigenetic_rates=c("+-"=0.01,"-+"=0.01),
                growth_rates=c("+"=0.2,"-"=0.08),
                death_rates=c("+"=0.1,"-"=0.01), 
                ancestor = "XXX",
                time =123
)
```

to denote a species `A` born at time 123 from a cell of species `A`. 

I propose we:

- manage in R the consistency check that the first species inserted has `ancestor = NULL` and `time = 0`.
- manage in R the consistency check that for any  species inserted (besides the first) the ancestor has already been insterted .
- manage in C++ the consistency that there are no loops across parent-child relations.

**Comment by caravagn** [comment]
Line 

```
# Program a timed transition from species "A" to
# species "B" at time 60
sim$add_timed_mutation("A", "B", 60)
```

is inconsistent with this specs as it should be `sim$add_species` to take the time as well.
