### ISSUE TITLE
Wrong cell file format Error

### ISSUE THREAD

**Issue by Militeee** [caravagnalab/rRACES#125]
Hi Alberto, I think I have the same problems as in issues  [#83](https://github.com/caravagnalab/rRACES/issues/83) but I am on a linux system this time.

The error I get is:
`Aiming cell id 58876 read Cell{id: 14959899108660452311, parent_id: 140737488306180, birth_time: 5.65959e-4942, species_id: 0}`

The code to reproduce the error is quite standard

```{r}
set.seed(seed_number)
 dir.create(glue::glue("/home/salvatore.milite/data/evoverse/synthetic_simulations/simulation_RACES/data/{id}"), showWarnings = FALSE)
setwd(glue::glue("/home/salvatore.milite/data/evoverse/synthetic_simulations/simulation_RACES/data/{id}"))
sim <- SpatialSimulation(seed = seed_number)
growth_rate = runif(1, 0.4, 0.8)
death_rate = runif(1,0.1,0.2)
sim$add_mutant(name = "A", growth_rates = growth_rate, death_rates =  death_rate)

sim$place_cell("A", 500, 500)
sim$run_up_to_size("A", 1e4)

plot_tissue(sim) %>% ggsave(glue::glue("/home/salvatore.milite/data/evoverse/synthetic_simulations/simulation_RACES/data/{id}/tissue_plot.pdf"), .)

# box specification
n_cells = 250 
bbox <- sim$search_samples(c("A" = n_cells), 50, 50,
                             n_samples=1)[[1]]
```

This is my session info:
![Screenshot 2024-12-03 at 18 07 46](https://github.com/user-attachments/assets/6429a3bc-724d-44f5-9aa0-0f53ea5f9ae5)
![Screenshot 2024-12-03 at 18 07 54](https://github.com/user-attachments/assets/ebfaf723-2fcb-45cb-9ef1-1d9ba9a6567b)

I used to get it just once in a while but now it became frequent, I guess it might be due to some cache that is already there but dunno. Also birth_time is always either super super small or NA it those cases.

**Comment by albertocasagrande** [comment]
@Militeee Can you post the full snippet producing the error (i.e., including the library imports and the definition of `seed_number`)?

**Comment by Militeee** [comment]
It is quite long so I paste it as txt, then I use it to generate an array of slurm job but the seed is simply a number from 1:100

```{r}
library(tidyverse)
source("utils_fun.R")

dir.create("data", showWarnings = TRUE)

config <- easypar::default_SBATCH_config()
config$`--nodes` <- "1"
config$`--partition` <- "cpuq"
config$`--job-name` <- "RACES_simulations"
config$`--cpus-per-task` <- "2"
config$`--mem-per-cpu` <- "16040M"
config$`--time` <- "3:00:00"

easypar_function <- function(id, seed_n){
  source("/home/salvatore.milite/data/evoverse/synthetic_simulations/simulation_RACES/utils_fun.R")
  neutral_template_races_sim_tissue(id, as.numeric(seed_n))
  
}


ids <- paste0("neutral_sim_", 1:100) 
seed <- 1:100
df_input <- data.frame(ids, seed)

easypar::run_SLURM(easypar_function, PARAMS = df_input, SBATCH_config = config, output_folder = "slurm_scripts/generate_neutral_sims", per_task = 1, N_simultaneous_jobs = 100, modules = "R/4.3.1")
```

[utils_fun.txt](https://github.com/user-attachments/files/17996755/utils_fun.txt)

**Comment by albertocasagrande** [comment]
I only need the R script and the seed value.

**Comment by albertocasagrande** [comment]
... or you can take care of your bug report, unravel all the conditions that produce the error, and relieve me from reverse engineering your slurm script.

**Comment by Militeee** [comment]
Well, I thought the main point of tool development was to have people actually being able to use your tool, but apparently, I am wrong...
Anyway, I added the SLURM part as a context not to waste your time but because the bug happens only when I run the simulations as array jobs through SLURM (I also just discovered that all the jobs share the same TMPDIR). When it is just the R script on an interactive session, it works fine, making me think about concurrent access to the same temporary file. If you tell me exactly the list of things you need to help you out I'll be more than happy to provide them

Cheers,
S.

**Comment by Militeee** [comment]
Problem solved, it was enough to to set `save_snapshots=TRUE` in `SpatialSimulation` (which I guess makes it save stuff in the working dir).
