### ISSUE TITLE
Generated files in the repository

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#13]
Some of the files in the directories `man` and `docs` of commit [2d2ff08](https://github.com/caravagnalab/rRACES/commit/2d2ff0837a7bbd331f5c638e7e3987b00c51f9d2) are automatically generated by `roxygen2` and `pkgdown`, respectively. 

These files should not be stored in the repository, but instead produced at building time. Maintaining them in the repository is a waste of space, may lead to bugs, and affects the cleanliness of the repository.

**Comment by caravagn** [comment]
I know, they were meant to show to you the rendering of the website. Will be removed at the next commits.
