### ISSUE TITLE
`get_cells`: get cells: returns a tibble of alive cells, including the cell id, the species and their tissue position

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#15]
```
cell_id | species | epistate | position_x | position_y
0x3423 | A | + | 3354 | 425
```

**Comment by caravagn** [comment]
Note, the new feature from commit [f5065f844732f5f90e61df7f7b6edad473f2838c] returns an empty dataframe

```
# Get the cells in the tissue at current simulation time
sim$get_cells()
```

**Comment by albertocasagrande** [comment]
What do you mean? Are you expecting something else? Can you provide a full example with the output and the expected result?

**Comment by caravagn** [comment]
It is just empty -- there are 0 rows.  I think it is a bug.

**Comment by caravagn** [comment]
```
> sim$get_cells()
[1] cell_id    species    epistate   position_x position_y
<0 rows> (or 0-length row.names)
```

**Comment by albertocasagrande** [comment]
On 75856a345a5d77a6e708c08acb801b4051235587, above code preceded by `require(rRACES)` produces a [this non-empty data frame](https://github.com/caravagnalab/rRACES/files/13196724/cells.csv).

**Comment by caravagn** [comment]
I see, I checked and you are correct if I do `library(rRACES)`. 

Still I get this

```
> x$simulation$get_counts()
  species epistate counts

1       A        - 111677
2       A        + 372696
3       B        -   1585
4       B        +  16071
```

but apparently no B cells are returned 

```
# Get the cells in the tissue at current simulation time
> x$simulation$get_cells(cells) %>% 
  group_by(species, epistate) %>% 
  summarise(n())

# A tibble: 2 × 3
# Groups:   species [1]
  species epistate  `n()`
  <chr>   <chr>     <int>
1 A       +        372696
2 A       -        111677
```

Are there any implicit filters applied by this function?

**Comment by albertocasagrande** [comment]
What is `x`? Have you tried to build a `tibble` using the output of `get_cells(cells)` before filtering it?

```R
tibble(x$simulation$get_cells(cells)) %>% 
  group_by(species, epistate) %>% 
  summarise(n())
```
