### ISSUE TITLE
RCpp/R bad constructor output folder

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#16]
It seems the R wrapper fails picking up the right Rcpp constructor @albertocasagrande and the output folder is always neglected as output folders have the form `races_3242343_345243` etc. disregarding the parameter.
 
https://github.com/caravagnalab/rRACES/blob/2dfd55f8b2f6ebb14f089a50f47254447dc73f6c/R/create_simulation.R#L18

Need to export also the seed and use the full constructor (not sure how I spec that).

**Comment by albertocasagrande** [comment]
I cannot confirm this behavior. On 75856a345a5d77a6e708c08acb801b4051235587, the following code
```R
sim <- new(rRACES::Simulation, "test_1234")

sim$add_species(name = "A", growth_rates = 0.25, death_rates = 0.05)

sim$add_cell(genotype_name = "A", x = 500, y = 500)

sim$run_up_to(60)
``` 

Create the directory `test_1234` and save the simulation data in it.

**Comment by caravagn** [comment]
I know it works in Rcpp, but it does not work here

```
x <- create_simulation(
  name = "My Test rRACES",
  output_dir = "some_folder",
  tissue = "A fake liver",
  tissue_size = c(4000, 4000)
)
```
where my R wrap is just this
```
#' create_simulation()
create_simulation = function(
    name = "My RACES simulation",
    output_dir = 'output_races',
    tissue = "Some tissue",
    tissue_size = c(1000, 1000)
)
{
  x = list()
  class(x) = 'rraces'
  
  ....
  
  # create a new simulation and save simulation data in "output_dir"
  x$simulation <- new(Simulation, output_dir)
  
  ....
}
```

**Comment by albertocasagrande** [comment]
Well, the Rcpp class `Simulation` is exported to R, so, either it works as expected or it does not. It may be a bug in `Simulation`, but I need to test some code to confirm it.

Can you provide a complete minimal example so that I can test it?

**Comment by albertocasagrande** [comment]
It was related to albertocasagrande/RACES#11. The issue is now solved.
