### ISSUE TITLE
`R CMD check --as-cran` produces 7 warning and 4 notes

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#17]
On 75856a345a5d77a6e708c08acb801b4051235587, the command `R CMD check --as-cran` produces 7 warning and 4 notes (see the file [00check.log](https://github.com/caravagnalab/rRACES/files/13196709/00check.log)). These warnings and nodes make `R CMD check` failing on github.

**Comment by caravagn** [comment]
Imho the package will never go on CRAN, because CRAN packages can only rely on other CRAN packages. I never felt CRAN the right place because of this constraints, in fact all our packages are hosted here on GitHub.

I think we should remove the `--as-cran`

**Comment by albertocasagrande** [comment]
The R-CMD-check on github fails because it uses the `--as-cran` options. Despite this, the package must be as clean as we can produce it, and we should pay attention to and possibly solve any warning raised by `R CMD check`.

Moreover, I think that we should consider the publication on CRAN. If some of the functionalities cannot be provided in CRAN, we may split the package into two different packages: the core rRACES package, which exclusively provides basic functionality, and an extended package (e.g., rRACES+), which relies on rRACES.

**Comment by caravagn** [comment]
I am not sure you really want to be on CRAN, it's really hard to depend ONLY on packages that are on CRAN. Also, splitting the wrapper is not an option. We can discuss this at the end though.

**Comment by luca-dex** [comment]
Despite the opportunity to publish or not to publish on CRAN, the warnings I see in the log are almost entirely related to the structure of the package itself and can be solved quite easily.

The only one that deserves a little more attention is the following:

```
* checking dependencies in R code ... WARNING
'::' or '::' imports not declared from:
  'RColorBrewer' 'tibble'
Namespace in Imports field not imported from: 'magrittr'.
  All declared Imports should be used.
```

**Comment by caravagn** [comment]
@luca-dex I know we would have caught your attention even from Mozambico ;)

**Comment by albertocasagrande** [comment]
All the original warnings are almost solved. One of them was due to the fact that `R CMD build` did not generate the documentation. After calling `roxygen2::roxygenise()`, new errors arise (!?!?!)

**Comment by albertocasagrande** [comment]
Apparently, `Rcpp` and `roxygen2` do not play well together. In particular, `roxygen2::roxygenize()` raises a WARNING because `Simulation` is exported but not present in `NAMESPACE` despite a line `export(Simulation)`. I wonder if the complaints are about `Simulation` methods rather than `Simulation` itself. In any case, the `R-CMD-check` action fails because of the `roxygen2` WARNING. 

We have three main alternatives:
1. getting rid of the `R-CMD-check` action and performing manually `R CMD check` (with works in any case) o `R CMD check --as-cran` (which fails because of the mentioned WARNING) only *after* executing `roxygen2::roxygenize()`. Of course, in this way, we will lose all the advantages of having an automatic test of the commit.
2. adding an action in `R-CMD-check` that calls `roxygen2::roxygenize()` *before* performing the real check. This solution was implemented in commit 621f2867b7232fbc6ac304efb153834714ef389e. Everything seems to work smoothly (except issue #24). Still, it forces us to call `roxygen2::roxygenize()` before building the package, and, in this way, we lose the ability to install the package directly from the GitHub repository. Moreover, this choice increases the execution time of the action.
3. committing to the repository the `*.Rd` files and updating them by calling `roxygen2::roxygenize()` before any commit. In this case, the `R-CMD-check` action works, and we can install the package from the GitHub repository, but we need to update the documentation *before* any commit. In this case, however, we can use a [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#:~:text=The%20pre%2Dcommit%20hook%20is,to%20inspect%20in%20the%20code) to force documentation generation before the commit.

@caravagn, what do you think?

**Comment by caravagn** [comment]
Pretty intricate situation. @luca-dex if I well remember you used Rcpp for some other package. Did you have to face a similar issue?

**Comment by albertocasagrande** [comment]
Hooray!!! I finally found a (weird) way to manage the issue. The `cleanup` script is executed **before** the package compilation. Calling `roxygenise()` from it without caution would produce a new building process that executes `cleanup` again in a never-ending loop. If we instead call `roxygenise()` only if
1. no documentation is available and
2. no other `roxygenise()` build is running,
we avoid the loop.
Point 1 can be implemented by testing the existence of file `man/Simulation.md`. Point 2 is trickier, but it can be achieved by creating a lock file before the call to `roxygenise()` and calling `roxygenise()` only if the lock file does not exist. 

The complete `cleanup` file is now the following one
```sh
rm -rf RACES _install _builds races_*

if [ ! -f man/Simulation.Rd ]; then
    if [ ! -f .roxygen.lock ]; then 
        touch .roxygen.lock

        ${R_HOME}/bin/R --vanilla --silent -e 'Rcpp::compileAttributes()'
        ${R_HOME}/bin/R --vanilla --silent -e 'roxygen2::roxygenise(roclets=c("rd"))'
        rm .roxygen.lock

        # This is to remove test byproducts
        rm -rf races_*
    fi
fi
```
