### ISSUE TITLE
Getters post-simulation, pre data generation

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#2]
- [x] #8
- [x] #4
- [x] #9
- [x] #11

- [x] #15
```
cell_id | species | epi-state | position_x | position_y
0x3423 | A | + | 3354 | 425
```
evaluate if we want to add extra parameters (eg, what portion of tissue to look at, or which species), or if we want actually leave this as a low-lever wrapper and export something higher-level (in R).

**Comment by caravagn** [comment]
OK do flag normal cells as species `WT` for consistency -- wildtype.

**Comment by caravagn** [comment]
Please @albertocasagrande do note I updated specs for functions names and output formats.

**Comment by albertocasagrande** [comment]
The proposed methods are part of the class `Simulation`, and any data from it is simulated. So, the `_simulated` substring in the method names seems unnecessary.

**Comment by caravagn** [comment]
I am not sure. Now we are now defining functions to query the whole state of a simulation. Later, we define samplings, how do we distinguish to query the number of cells in a sampled region versus the overall number of simulated cells?

**Comment by albertocasagrande** [comment]
What about `get_cells(lower_corner, upper_corner)` to sample the tissue versus `get_cells()` to the whole tissue data?

**Comment by caravagn** [comment]
Seems reasonable, so you mean without parameters for species/epistates filters?

**Comment by albertocasagrande** [comment]
Let us initially focus on a naive version of the API. Filters will come after it.
