### ISSUE TITLE
Species vs Genotype

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#20]
The difference between species and genotype needs to be clarified in the API.

A species is a cell set with the same duplication, death, and epigenetic mutation rates. Thus, the call 

```R
sim$add_speces(name="A", 
               epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
               growth_rates = c("+" = 0.2, "-" = 0.08),
               death_rates = c("+" = 0.1, "-" = 0.01))
```

defines two species: namely, `A+` and `A-`. 

Even though we still don't know their genetic characterization, `A+` and `A-` are identical from the genomic point of view, and they exclusively differ because of their epigenetic state. Thus, `A` is their genotype name.

Do you agree with this terminology, @caravagn?

**Comment by caravagn** [comment]
I think you raise a good point here. So you suggest that every function should be renamed, for example `get_cells` instead of
```
cell_id | species | epistate | position_x | position_y
0x3423 | A | + | 3354 | 425
```
it should return
```
cell_id | genotypes | epistate | position_x | position_y
0x3423 | A | + | 3354 | 425
```
If yes, I agree.  I would however leave `epistate` as such because `epigenotype` might be a little too much for a simple +/- state
