### ISSUE TITLE
Better naming of `add_timed_mutation`

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#21]
I think the terminology `add_timed_mutation` might be misleading because we do not necessarily have a "mutation" to explain passage from population `A` to `B`, but it could be a copy number or any other type of alteration we might include in the future.

I think what we actually do with that function is to "link" - in an evolutionary sense - two genotypes (not even two species, based on our recent renaming) in a linear evolutionary relation. 

How about we call it any of:

-  `link_genotype`
-  `add_linear_evolution`
- `link_?`

**Comment by caravagn** [comment]
Of course, a possibility is that you keep it named like that in the Rcpp interface, and I expose it in R with a different name.

**Comment by albertocasagrande** [comment]
What about `add_genotype_evolution`?

**Comment by albertocasagrande** [comment]
`schedule_evolution`?
