### ISSUE TITLE
Garbage committed to the repository

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#5]
The commit [75b7df7](https://github.com/caravagnalab/rRACES/commit/75b7df79eb351f1c93dd084c5dbee9834f11eab5) contains directories and files that are not supposed to be submitted to the repository. 

In particular, 
- `./_builds` and its content
- `./_install` and its content
- `./output_dir` and its content
- `./src/RACES.so`
- `./src/libRACES.so`
- `./src/drivers.o`
- `./rRACES.Rproj`

are not part of the wrapper source and must be removed from the repository.

**Comment by caravagn** [comment]
Closed with f3ee65c550edd6e11f287c312c83f11aeb9d0cbf
