### ISSUE TITLE
`plot_muller` produces discontinuous plots

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#50]
`plot_muller` produces discontinuous plots like the ones below.

![image](https://github.com/caravagnalab/rRACES/assets/11404904/c9214db7-2412-4ae8-9e5f-f8ec5bd327ab)

(between time 87 and time 89)

![image](https://github.com/caravagnalab/rRACES/assets/11404904/6cdf2d26-4101-4aea-995d-219ec4ec0aa7)

(at the bottom of the plot around time 67)

As far as I know, Muller plots should be continuous. Am I wrong?

**Comment by caravagn** [comment]
Well I think that maybe that is just the effect of using a log-scale on `y` as it comes with the last code at [the vignette](https://caravagnalab.github.io/rRACES/articles/a01_tissue_simulation.html)?

Maybe it is because the population reaches 0? It is a bit a surprise the y-axis label though.

**Comment by albertocasagrande** [comment]
This seems to be a `ggmuller` bug. We may signal it.
