### ISSUE TITLE
`Rcpp_Simulation$show` raises errors

### ISSUE THREAD

**Issue by albertocasagrande** [caravagnalab/rRACES#51]
The version of `Rcpp_Simulation$show` introduced by commit dfa2e4b0fa7b31add194277db8cf473e6a34fa5e  raises errors.

**Comment by albertocasagrande** [comment]
Added a temporary fix in commit 704a78ca4067bd261f778347f81f3a0d406e0fa9.

**Comment by caravagn** [comment]
Saw that while I was already fixing -- just pushed and it should work. Will close upon confirmation
