### ISSUE TITLE
Growth model

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#52]
The models in the vignette gives the same MRCAs, and therefore the vignette/ implementation does not seem very convincing.  I do not have an intuition on why this happens.

I added a visualisation to highlight lineages in the tree -- it might help figure out.

Also, the model with the boundary-driven growth (as we usually call it), should be the default. Otherwise all other plots in the vignettes have those unexpected MRCAs.

**Comment by albertocasagrande** [comment]
When using the boundary-driven growth model, the samples on the tumor border are those having younger cells on average. Thus, their MRCAs tend to be younger than the internal cells. 

To highlight the differences between the supported growth models, it would be preferable to always select samples on the tumor border. However, the function `Simulation$search_sample` does not choose samples near the tumor border.

Commit 2b3a0c4f1d7d7cefa706a5ace73bfc5d6437e1aa added a sentence in the "Growth Models" article to stress the need to choose samples on the border to highlight a stricter relation between spatial and genetic distance when border-driven growth model.
