### ISSUE TITLE
sim$get_forest() bug

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#53]
When i load a simulation and sample cells with the code:

```R

library(rRACES)
library(ggplot2)

sim = recover_simulation("races_1_230")
sim

current <- plot_tissue(sim)
current

bbox_width <- 100

bbox1_p <- c(5000, 5000)
bbox1_q <- bbox1_p + bbox_width

sim$sample_cells("sampling", bottom_left = bbox1_p, top_right = bbox1_q)

samples_forest = sim$get_samples_forest() 

```

at the last command Rstudio aborts.

**Comment by albertocasagrande** [comment]
Can you provide also the simulation example? 

In the last week, RACES data structures have been under deep revision, thus, it could be the case that the old simulation is no more supported. Before the release of a stable version, we will take care of this kind of issue.

**Comment by riccardobergamin** [comment]
yes,sure. I sent it to you on Slack

**Comment by albertocasagrande** [comment]
@riccardobergamin I meant the R script that produced the directory.

**Comment by riccardobergamin** [comment]
``
  sample = m
        sim <- new(Simulation, paste0(folder, "races_simulations/races_",
            batch, "_", sample), seed = m)
        sim$update_tissue("Liver", 10000, 10000)
        sim$add_genotype(name = "A", epigenetic_rates = c(`+-` = rn,
            `-+` = rp), growth_rates = c(`+` = lambda_p, `-` = lambda_n),
            death_rates = c(`+` = 0, `-` = 0))
        sim$place_cell("A-", 5000, 5000)
        counts = sim$get_counts() %>% mutate(time = sim$get_clock())
        times = seq(1, Time, 1)
        for (t in times) {
            sim$run_up_to_time(t)
            counts = rbind(counts, sim$get_counts() %>% as_tibble() %>%
                mutate(time = sim$get_clock()))
        }
        counts = counts %>% as_tibble() %>% mutate(sample = m)
        switch_table = sim$get_lineage_graph() %>% as_tibble()
``

**Comment by albertocasagrande** [comment]
I have tested successfully the two blocks of code by using the same version of rRACE. Some of the data were missing from the latter block (e.g., `m`, `batch`, `folder`, `Time`), so , I randomly chose them. 

As I wrote above, my guess is that you tried to load a simulation produced by an older version of rRACES and this is not supported at the moment.
