### ISSUE TITLE
problem with plot_tissue()

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#60]
I have an example of expansion with tow phenotypes and one phenotype simulated in this way:

``
sim <- new(Simulation, "vaf test",seed = 1, save_snapshot = F)

sim$duplicate_internal_cells <- F

sim$update_tissue("Liver", 4e3, 4e3)

sim$add_mutant(name = "A",
               epigenetic_rates = c("+-" = 0.01, "-+" = 0.01),
               growth_rates = c("+" = 1.5, "-" =  1.5),
               death_rates = c("+" = 0, "-" = 0))

sim$place_cell("A-", 2000, 2000)

sim$run_up_to_time(t = 400)

``

i got: 
<img width="1146" alt="Screenshot 2024-01-17 alle 11 43 16" src="https://github.com/caravagnalab/rRACES/assets/72212720/65be780c-bc25-44fe-b30e-2aec8b093547">

then using plot_tissue(sim) i got 

``
bbox = tibble(lower_corner = c(1990,1990),upper_corner = c(2010,2010))
current = plot_tissue(sim)

current = current +
  geom_rect(xmin = bbox$lower_corner[1], xmax = bbox$upper_corner[1],
            ymin = bbox$lower_corner[2], ymax = bbox$upper_corner[2],
            fill = NA, color = "black")
``

<img width="832" alt="Screenshot 2024-01-17 alle 11 42 54" src="https://github.com/caravagnalab/rRACES/assets/72212720/0dab9f08-cd23-4875-b370-795b2bda5e1e">

is it normal? it seems there is only A+

**Comment by albertocasagrande** [comment]
The function `plot_tissue` depicts the tissue by splitting it into a limited number of bins and plotting them. Each bin's color represents the species with the maximum number of cells in it. 
What you see means that  "A+" is the most numerous species in most of the bins.

A finer representation can be obtained by increasing the number of bins.

I plotted the tissue obtained by the above model, issuing `plot_tissue(sim, num_of_bins=1000)` and got the following image.

![Rplot](https://github.com/caravagnalab/rRACES/assets/11404904/f0756121-cd92-49ec-84f0-3e01f917b475)

**Comment by riccardobergamin** [comment]
ok, thank you!!!
