### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by ElenaRivaroli** [caravagnalab/rRACES#61]
I am trying to install rRACES with devtools, but I am getting the following error:

In file included from cna.cpp:18:
cna.hpp:23:10: fatal error: cna.hpp: No such file or directory
   23 | #include <cna.hpp>
      |          ^~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-43~1.2/etc/x64/Makeconf:272: cna.o] Error 1
ERROR: compilation failed for package 'rRACES'

How can I solve it?

**Comment by albertocasagrande** [comment]
rRACES does not support Windows at the moment.

**Comment by ElenaRivaroli** [comment]
Okay, thanks anyway.
