### ISSUE TITLE
SNVS in sequencing does not match the ones in phylogenetic forest

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#77]
I am running the following code

```
library(rRACES)

reference_url <- paste0("https://ftp.ensembl.org/pub/grch37/current/",
                        "fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.",
                        "dna.chromosome.22.fa.gz")

SBS_url <- paste0("https://cancer.sanger.ac.uk/signatures/documents/2123/",
                  "COSMIC_v3.4_SBS_GRCh37.txt")

drivers_url <- paste0("https://raw.githubusercontent.com/",
                      "caravagnalab/rRACES/main/inst/extdata/",
                      "driver_mutations_hg19.csv")

passenger_CNAs_url <- paste0("https://raw.githubusercontent.com/",
                             "caravagnalab/rRACES/main/inst/extdata/",
                             "passenger_CNAs_hg19.csv")

germline_url <- paste0("https://www.dropbox.com/scl/fi/g9oloxkip18tr1r",
                       "m6wjve/germline_data_demo.tar.gz?rlkey=15jshul",
                       "d3bqgyfcs7fa0bzqeo&dl=1")

m_engine <- build_mutation_engine(directory = "Test",
                                  reference_src = reference_url,
                                  SBS_src = SBS_url,
                                  drivers_src = drivers_url,
                                  passenger_CNAs_src = passenger_CNAs_url,
                                  germline_src = germline_url)


m_engine$add_mutant(mutant_name = "A",
                    passenger_rates = list("+" = c(SNV = 5e-9), 
                                           "-" = c(SNV = 5e-9)),
                    driver_SNVs = c(), driver_CNAs = c())

m_engine$add_exposure(c(SBS1=0.2, SBS5=0.8))

sim <- new(Simulation,
               seed = sample(x = 1:1000,size = 1),
               save_snapshot = F)
    
sim$duplicate_internal_cells <- T
    
sim$update_tissue("Liver", 2e3, 2e3)
    
    # plastic 
    
    sim$add_mutant(name = "A",
                   epigenetic_rates = c("+-" = 0.001, "-+" = 0.001),
                   growth_rates = c("+" = 5,"-" =  1),
                   death_rates = c("+" = 0.0, "-" = 0.0))
    sim$place_cell("A-", 1e3, 1e3)
    
    sim$run_up_to_size("A+",1e5)
    
    n_w <- n_h <- 50
    ncells <- 0.8*n_w*n_h
    bbox <- sim$search_sample(c("A" = ncells), n_w, n_h)
    
    sim$sample_cells("Sampling", bbox$lower_corner, bbox$upper_corner)
    
    forest <- sim$get_samples_forest()

  phylo_forest <- m_engine$place_mutations(forest,500)
  
  print(phylo_forest)
```

printing the phylogenetic forest i get 
<img width="228" alt="Screenshot 2024-02-24 alle 22 26 14" src="https://github.com/caravagnalab/rRACES/assets/72212720/f7d0579d-039f-4e83-98df-cfbc3a41c317">

But then in the sequencing

```
  seq_results <-
    simulate_seq(
      phylo_forest,
      coverage = 150,
      epi_FACS =  T,
      write_SAM = F
    )
library(dplyr)
 print(seq_results %>% as_tibble()) 
```
i obtain mutations that should not be in the forest

<img width="940" alt="Screenshot 2024-02-24 alle 22 26 26" src="https://github.com/caravagnalab/rRACES/assets/72212720/3ceb76b7-b9db-409a-8db0-f789c0411ef9">

```
 phylo_forest$get_first_occurrences(SNV(chromosome = seq_results$chromosome[1],
                                        pos_in_chr = seq_results$chr_pos[1],
                                        alt = seq_results$alt[1],
                                        ref = seq_results$ref[1]
    ))

```
Indeed 
<img width="689" alt="Screenshot 2024-02-24 alle 22 26 35" src="https://github.com/caravagnalab/rRACES/assets/72212720/858a31ec-1b02-45e3-b545-317dec115e92">

Am i doing something wrong?

**Comment by albertocasagrande** [comment]
The selected mutation is a germline mutation. Because of that `get_first_occurrences` fail to identify the nodes in the phylogenetic forest in which it occurs the first time. 

Would you prefer a different error message or a fake "wild-type" node id?

**Comment by riccardobergamin** [comment]
ok, i see. Would be better an option than does not include germlines in the sequencing? or a label saying if its sequencing? AI think a different error message is ok rather than more nodes

**Comment by caravagn** [comment]
I think that by default we might have germlines not returned via a flag @albertocasagrande. I would use a flag with default False. The same could apply for preneoplastic and tumour (passenger) and tumour driver etc. it would be great if the getters have a column to specify the mutation class. Would this solve everything?

**Comment by riccardobergamin** [comment]
Yes, i think it is fine if in the phylogenetic forest the mutations are classified. By default i think it would be more natural to include only somatic in the sequencing.

**Comment by albertocasagrande** [comment]
We can univocally label phylogenetic forest mutations but not sequencing mutations: the same mutation may be preneoplastic in one forest tree and passenger in another. That is why I wrote that the next release will label forest mutations.

However, the mentioned problematic labeling is unlikely and only affects multiple-tree forests. So, if you are happy with a set label that does not report the numerosity (e.g., `c("preneoplastic", "passenger")` or `"preneoplastic, passenger"`), I can implement it. In most of the cases, a single label will be returned (e.g., `c("passenger")` or `"passenger"`).

@caravagn, @riccardobergamin, if you agree with the set label solution, let me know if you prefer a vector labeling (e.g., `c("preneoplastic", "passenger")` or a string labeling (e.g., `"preneoplastic, passenger"`).

**Comment by riccardobergamin** [comment]
Can it happen that germline are flagged as SBS1, or they should have just cause = "NA"?
