### ISSUE TITLE
error with mutation engine loading on unix

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#78]
When i build the mutation engine from an existing folder on Unix i am getting an error of "bad allocation":

<img width="749" alt="Screenshot 2024-02-25 alle 11 57 36" src="https://github.com/caravagnalab/rRACES/assets/72212720/cf89e5ec-9bee-4238-8ba4-ead601d9a1f6">

**Comment by albertocasagrande** [comment]
Is it a folder created by a previous version of rRACES?

**Comment by riccardobergamin** [comment]
no, i created with the same version

**Comment by albertocasagrande** [comment]
Can you try to create a new directory and reload it, please?

**Comment by riccardobergamin** [comment]
yes,sure:

`  
library(rRACES)

reference_url <- paste0("https://ftp.ensembl.org/pub/grch37/current/",
                          "fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.",
                          "dna.chromosome.22.fa.gz")
  
  SBS_url <- paste0("https://cancer.sanger.ac.uk/signatures/documents/2123/",
                    "COSMIC_v3.4_SBS_GRCh37.txt")
  
  drivers_url <- paste0("https://raw.githubusercontent.com/",
                        "caravagnalab/rRACES/main/inst/extdata/",
                        "driver_mutations_hg19.csv")
  
  passenger_CNAs_url <- paste0("https://raw.githubusercontent.com/",
                               "caravagnalab/rRACES/main/inst/extdata/",
                               "passenger_CNAs_hg19.csv")
  
  germline_url <- paste0("https://www.dropbox.com/scl/fi/g9oloxkip18tr1r",
                         "m6wjve/germline_data_demo.tar.gz?rlkey=15jshul",
                         "d3bqgyfcs7fa0bzqeo&dl=1")
  
  m_engine <- build_mutation_engine(directory = "Test"
                                    reference_src = reference_url,
                                    SBS_src = SBS_url,
                                    drivers_src = drivers_url,
                                    passenger_CNAs_src = passenger_CNAs_url,
                                    germline_src = germline_url)

m_engine <- build_mutation_engine(directory = "Test"
                                    reference_src = reference_url,
                                    SBS_src = SBS_url,
                                    drivers_src = drivers_url,
                                    passenger_CNAs_src = passenger_CNAs_url,
                                    germline_src = germline_url)

`
the second time i use build_mutation_engine i get the error

**Comment by albertocasagrande** [comment]
Can you provide the output of the command `uname -a`?

**Comment by riccardobergamin** [comment]
yes, i get:

Linux epyc001.hpc.rd.areasciencepark.it 6.1.13-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 18:13:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
