### ISSUE TITLE
`get_info`: get current simulation info.

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#8]
Tibble format
```
field | value
--------------------
name | "My Simulation"
tissue | "Liver"
tissue_size | 100x100
```

Visualisation: none, but will be used to augment other visualisations.

**Comment by caravagn** [comment]
Proposed format

```
field | value
--------------------
name | "My Simulation"
tissue | "Liver"
tissue_size | 100x100
```

**Comment by albertocasagrande** [comment]
Rcpp does not support tibble. Would you prefer three different method:
1. `get_name()` returning a string
2. `get_tissue_name()` returning a string
3. `get_tissue_size()` returning a vector of integers

in place of `get_info()`?

**Comment by caravagn** [comment]
Ok!

**Comment by albertocasagrande** [comment]
The semantics of the method `get_name()` is unclear. I will replace it by `get_directory()`.
