### ISSUE TITLE
karyotype column

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#80]
I think would be a good idea to return in the function  simulate_seq() also the karyotype of the mutation (1:1,2:0,2:1,2:2), or two columns with Major and minor allele.

**Comment by caravagn** [comment]
How can this unique if you have a clone with a subclonal CNA?

**Comment by riccardobergamin** [comment]
I think we may close it, we can just map mutations on segments with a dedicated function.
