### ISSUE TITLE
problem with muller plot

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#85]
I am getting an error with the function plot_muller()

```
library(rRACES)

sim <- new(Simulation, "homogeneous_test",seed = sample(x = 1:5000,size = 1,replace = F),
           save_snapshot = F)

sim$duplicate_internal_cells <- T

sim$update_tissue("Liver", 2e3, 2e3)

sim$add_mutant(name = "A",
               growth_rates = 1,
               death_rates = 0)


sim$place_cell("A", 1e3, 1e3)


sim$run_up_to_size("A",1e4)

sim$add_mutant(name = "B",
               growth_rates = 3.5,
               death_rates = 0)

sim$mutate_progeny(sim$choose_cell_in("A"), "B")

sim$run_up_to_size("B",1e4)

plot_muller(sim)
```

<img width="741" alt="Screenshot 2024-02-28 alle 12 07 18" src="https://github.com/caravagnalab/rRACES/assets/72212720/42407b43-dd9e-4b53-8c0a-7b8865936e84">

<img width="1031" alt="Screenshot 2024-02-28 alle 12 12 11" src="https://github.com/caravagnalab/rRACES/assets/72212720/8896013a-1561-4321-a553-fc1ab5906444">

**Comment by albertocasagrande** [comment]
I ran it 100 times with success on a MacBook with 16GB of RAM having macOS Sonoma 14.3.1.

On which system are you executing the script? Can you provide the exact seed on which the script fail?

**Comment by albertocasagrande** [comment]
Closed because of the lack of feedback.
