### ISSUE TITLE
`get_counts`: get number of cells per species, at last stop.

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#9]
Tibble format
```
species | epistate | counts
 ---------------
A | + | 1000
A | - | 400
B | + | 102
C | - | 455
```

Visualisation function: [https://github.com/caravagnalab/rRACES/blob/main/R/plot_counts.R](plot_counts)

**Comment by caravagn** [comment]
Proposed format

```
 species | epi-state | n
 ---------------
A | + | 1000
A | - | 400
B | + | 102
C | - | 455
```

**Comment by caravagn** [comment]
The visualisation function linked with this getter is  [https://github.com/caravagnalab/rRACES/blob/main/R/plot_counts.R](plot_counts)

**Comment by albertocasagrande** [comment]
What about replacing column name "n" with "counts"?

**Comment by caravagn** [comment]
OK sure let's replace that. Let's be consistent though and every `n` will be a `count`.
