### ISSUE TITLE
Add SM tag in RG filed of simulated SAM files

### ISSUE THREAD

**Issue by giorgiagandolfi** [caravagnalab/rRACES#91]
I am testing sarek variant calling staring from `sam` files generated by both `simulate_seq` and `simulate_normal_seq`. I would suggest to add to the `@RG` field in `sam` header the `SM` tag, since most steps of the analysis require it. In general the `SM` tag refers to the sample name, which is unique.
Here an example:
```
@HD   VN:1.6 SO:unknown
@SQ   SN:22  LN:51304566   AN:chromosome22,chr22,chromosome_22,chr_22
@RG   ID:S1_1   SM:S1
@RG   ID:S1_2   SM:S1
```

**Comment by albertocasagrande** [comment]
In the header produced by RACES, IDs are the sample names. So, if this matches your request, we can produce a header of the kind
```{r}
@HD   VN:1.6 SO:unknown
@SQ   SN:22  LN:51304566   AN:chromosome22,chr22,chromosome_22,chr_22
@RG   ID:S1_1   SM:S1_1
@RG   ID:S1_2   SM:S1_2
```

**Comment by giorgiagandolfi** [comment]
Yes, sorry you're right. So if I would like to have a sam specific for each sample, I will split the sam.
Thanks

**Comment by albertocasagrande** [comment]
You can already split the SAM as described in the [documentation](https://caravagnalab.github.io/rRACES/articles/sequencing.html#saving-the-simulated-reads).

In any case, do you think I should add the SM tag as suggested above?
