### ISSUE TITLE
run_up_to_size

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/rRACES#93]
The logic of `run_up_to_size` is currently limiting, as it assumes that if the state has `n` cells any state with `m <n`  cells is already reached (no computation). This makes it hard to model therapy effects, where you have `n` starting cells and want to reach a state with ~100 cells, for instance.

Since you have the ESC key intercepted, change the logic to 'I compute until I reach the desired state'.

**Comment by albertocasagrande** [comment]
Closed by commit 34be9dd49f57e421a67113becd9d0c8d8ae40966. Use [formulas and `Simulation$run_until()`](https://caravagnalab.github.io/rRACES/articles/tissue_simulation.html#formula-based-simulation-advanced).

**Comment by caravagn** [comment]
Wow this is faboulous (the logic) and deserves being explained to the guys
